//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_CommerceF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ecommerceEntities : DbContext
    {
        public ecommerceEntities()
            : base("name=ecommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGENTE_VENTA> AGENTE_VENTA { get; set; }
        public virtual DbSet<ALMACEN> ALMACEN { get; set; }
        public virtual DbSet<CATEGORIA> CATEGORIA { get; set; }
        public virtual DbSet<CHAT> CHAT { get; set; }
        public virtual DbSet<DEVOLUCION_PEDIDO> DEVOLUCION_PEDIDO { get; set; }
        public virtual DbSet<DIRECCION> DIRECCION { get; set; }
        public virtual DbSet<FACTURA> FACTURA { get; set; }
        public virtual DbSet<FACTURA_PRODUCTO> FACTURA_PRODUCTO { get; set; }
        public virtual DbSet<IMAGEN_PRODUCTO> IMAGEN_PRODUCTO { get; set; }
        public virtual DbSet<METODO_PAGO> METODO_PAGO { get; set; }
        public virtual DbSet<ORDEN> ORDEN { get; set; }
        public virtual DbSet<ORDEN_PRODUCTO> ORDEN_PRODUCTO { get; set; }
        public virtual DbSet<PEDIDO_PROVEEDOR> PEDIDO_PROVEEDOR { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<PRODUCTO_PEDIDO> PRODUCTO_PEDIDO { get; set; }
        public virtual DbSet<PRODUCTO_PROMOCION> PRODUCTO_PROMOCION { get; set; }
        public virtual DbSet<PRODUCTO_PROVEEDOR> PRODUCTO_PROVEEDOR { get; set; }
        public virtual DbSet<PROMOCION> PROMOCION { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<TIPO_PROMOCION> TIPO_PROMOCION { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<HISTORIAL_PRECIO> HISTORIAL_PRECIO { get; set; }
    }
}
